name: CAT

on:
  push:
    branches: [ ci-experiment/** ]
  workflow_dispatch:
    inputs:
      rounds:
        description: "Number of Rounds"
        type: number
        required: true
        default: 10

jobs:
  ai_tests:
    name: AI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set number of runs
        id: set-number-of-runs
        run: |
          ROUNDS=${{ inputs.rounds || 10 }}
          echo "::notice::Starting $ROUNDS runs"
          echo "number_of_runs=$ROUNDS" >> "$GITHUB_OUTPUT"
          echo "CAT_AI_SAMPLE_SIZE=$ROUNDS" >> $GITHUB_ENV

      - name: Run Example tests
        run: uv run pytest examples/team_recommender/tests/example_6_n_generations/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

#      - name: Upload artifacts to MinIO
#        run: |
#          zip -r test-output-${{ github.run_number }}.zip examples/team_recommender/tests/test_runs
#            curl -X PUT -T "/path/to/yourfile.zip" \
#            -H "Host: localhost:9000" \
#            -H "Date: $(date -R)" \
#            -H "Content-Type: application/zip" \
#            -H "Authorization: AWS minioadmin:minioadmin" \
#            http://localhost:9000/yourbucket/yourfile.zip

      - name: Show number of test failures
        if: always()
        run: |
          FAILURES=$(find examples/team_recommender/tests/test_runs -type f -name "fail-*" | wc -l)
          .github/workflows/calculate-error-margin.sh $FAILURES $CAT_AI_SAMPLE_SIZE >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts to Google Drive
        if: always()
        run: |
          zip -r test-output-${{ github.run_number }}.zip examples/team_recommender/tests/test_runs
          uv run python src/cat_ai/publish_to_gdrive.py test-output-${{ github.run_number }}.zip
        env:
          GOOGLE_DRIVE_TEST_OUTPUT_FOLDER_ID: ${{ vars.GOOGLE_DRIVE_TEST_OUTPUT_FOLDER_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: test-output-${{ github.run_number }}
            path: examples/team_recommender/tests/test_runs

#      - name: Debugging with tmate
#        if: failure()
#        uses: lhotari/action-upterm@v1
#        with:
#          wait-timeout-minutes: 5
